apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: voting-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker

          image: zeeshankhan001/worker-app-image:latest

          envFrom:
            - configMapRef:
                name: app-config

            - secretRef:
                name: postgres-secret

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"